POST localhost:8080/api/v1/login HTTP/1.1

Christoph Lofi

###

POST localhost:8080/api/v1/create HTTP/1.1
token: a1758197-68d1-4a0e-814c-ac9540ecc8eb
scheduledTime: 0

OOPP

###

POST localhost:8080/api/v1/login HTTP/1.1

Stephan

###

GET localhost:8080/api/v1/join HTTP/1.1
Token: 10fba5a7-2b18-4474-bb48-72ca7cc67a37
Code: 7tUl8v

###

GET localhost:8080/api/v1/participants HTTP/1.1
Token: 10fba5a7-2b18-4474-bb48-72ca7cc67a37
RoomId: 1

###

POST localhost:8080/api/v1/ask HTTP/1.1
Token: 10fba5a7-2b18-4474-bb48-72ca7cc67a37
RoomId: 1

ok.

###

DELETE localhost:8080/api/v1/question/2 HTTP/1.1
Token: 10fba5a7-2b18-4474-bb48-72ca7cc67a37

###

POST localhost:8080/api/v1/login HTTP/1.1

Stefan

###

GET localhost:8080/api/v1/join HTTP/1.1
Token: cb257ed6-bfcf-4c0c-9724-8e72647adff4
Code: miSzbd
